# Generated by Django 3.2.5 on 2021-08-19 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=75, verbose_name='title')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='description')),
            ],
        ),
        migrations.CreateModel(
            name='YorubaTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Yoruba_title', models.CharField(max_length=100)),
                ('Yoruba_explanations', models.TextField()),
                ('en_title', models.CharField(max_length=100)),
                ('en_explanations', models.TextField()),
                ('ig_title', models.CharField(max_length=100)),
                ('ig_explanations', models.TextField()),
                ('ha_title', models.CharField(max_length=100)),
                ('ha_explanations', models.TextField()),
                ('yo_title', models.CharField(max_length=100)),
                ('yo_explanations', models.TextField()),
                ('fr_title', models.CharField(max_length=100)),
                ('fr_explanations', models.TextField()),
                ('ar_title', models.CharField(max_length=100)),
                ('ar_explanations', models.TextField()),
                ('category', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Alteernlingual_topic.category', verbose_name='category')),
            ],
        ),
        migrations.CreateModel(
            name='IgboTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Igbo_title', models.CharField(max_length=100)),
                ('Igbo_explanations', models.TextField()),
                ('en_title', models.CharField(max_length=100)),
                ('en_explanations', models.TextField()),
                ('ig_title', models.CharField(max_length=100)),
                ('ig_explanations', models.TextField()),
                ('ha_title', models.CharField(max_length=100)),
                ('ha_explanations', models.TextField()),
                ('yo_title', models.CharField(max_length=100)),
                ('yo_explanations', models.TextField()),
                ('fr_title', models.CharField(max_length=100)),
                ('fr_explanations', models.TextField()),
                ('ar_title', models.CharField(max_length=100)),
                ('ar_explanations', models.TextField()),
                ('category', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Alteernlingual_topic.category', verbose_name='category')),
            ],
        ),
        migrations.CreateModel(
            name='HausaTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Hausa_title', models.CharField(max_length=100)),
                ('Hausa_explanations', models.TextField()),
                ('en_title', models.CharField(max_length=100)),
                ('en_explanations', models.TextField()),
                ('ig_title', models.CharField(max_length=100)),
                ('ig_explanations', models.TextField()),
                ('ha_title', models.CharField(max_length=100)),
                ('ha_explanations', models.TextField()),
                ('yo_title', models.CharField(max_length=100)),
                ('yo_explanations', models.TextField()),
                ('fr_title', models.CharField(max_length=100)),
                ('fr_explanations', models.TextField()),
                ('ar_title', models.CharField(max_length=100)),
                ('ar_explanations', models.TextField()),
                ('category', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Alteernlingual_topic.category', verbose_name='category')),
            ],
        ),
        migrations.CreateModel(
            name='FrenchTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('French_title', models.CharField(max_length=100)),
                ('French_explanations', models.TextField()),
                ('en_title', models.CharField(max_length=100)),
                ('en_explanations', models.TextField()),
                ('ig_title', models.CharField(max_length=100)),
                ('ig_explanations', models.TextField()),
                ('ha_title', models.CharField(max_length=100)),
                ('ha_explanations', models.TextField()),
                ('yo_title', models.CharField(max_length=100)),
                ('yo_explanations', models.TextField()),
                ('fr_title', models.CharField(max_length=100)),
                ('fr_explanations', models.TextField()),
                ('ar_title', models.CharField(max_length=100)),
                ('ar_explanations', models.TextField()),
                ('category', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Alteernlingual_topic.category', verbose_name='category')),
            ],
        ),
        migrations.CreateModel(
            name='EnglishTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('English_title', models.CharField(max_length=100)),
                ('English_explanations', models.TextField()),
                ('en_title', models.CharField(max_length=100)),
                ('en_explanations', models.TextField()),
                ('ig_title', models.CharField(max_length=100)),
                ('ig_explanations', models.TextField()),
                ('ha_title', models.CharField(max_length=100)),
                ('ha_explanations', models.TextField()),
                ('yo_title', models.CharField(max_length=100)),
                ('yo_explanations', models.TextField()),
                ('fr_title', models.CharField(max_length=100)),
                ('fr_explanations', models.TextField()),
                ('ar_title', models.CharField(max_length=100)),
                ('ar_explanations', models.TextField()),
                ('category', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Alteernlingual_topic.category', verbose_name='category')),
            ],
        ),
        migrations.CreateModel(
            name='ArabicTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Arabic_title', models.CharField(max_length=100)),
                ('Arabic_explanations', models.TextField()),
                ('en_title', models.CharField(max_length=100)),
                ('en_explanations', models.TextField()),
                ('ig_title', models.CharField(max_length=100)),
                ('ig_explanations', models.TextField()),
                ('ha_title', models.CharField(max_length=100)),
                ('ha_explanations', models.TextField()),
                ('yo_title', models.CharField(max_length=100)),
                ('yo_explanations', models.TextField()),
                ('fr_title', models.CharField(max_length=100)),
                ('fr_explanations', models.TextField()),
                ('ar_title', models.CharField(max_length=100)),
                ('ar_explanations', models.TextField()),
                ('category', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Alteernlingual_topic.category', verbose_name='category')),
            ],
        ),
    ]
