# Generated by Django 3.2.5 on 2023-01-17 15:02

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='title')),
                ('main_explanations', ckeditor_uploader.fields.RichTextUploadingField(blank=True, default=None, null=True)),
                ('EN_explanations', ckeditor_uploader.fields.RichTextUploadingField(blank=True, default=None, null=True)),
                ('read_by', models.ManyToManyField(blank=True, related_name='read_topics', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
