# Generated by Django 3.2.5 on 2021-08-22 19:51

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Alteernlingual_topic', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='arabictopic',
            name='ar_explanations',
        ),
        migrations.RemoveField(
            model_name='arabictopic',
            name='ar_title',
        ),
        migrations.RemoveField(
            model_name='arabictopic',
            name='en_explanations',
        ),
        migrations.RemoveField(
            model_name='arabictopic',
            name='en_title',
        ),
        migrations.RemoveField(
            model_name='arabictopic',
            name='fr_explanations',
        ),
        migrations.RemoveField(
            model_name='arabictopic',
            name='fr_title',
        ),
        migrations.RemoveField(
            model_name='arabictopic',
            name='ha_explanations',
        ),
        migrations.RemoveField(
            model_name='arabictopic',
            name='ha_title',
        ),
        migrations.RemoveField(
            model_name='arabictopic',
            name='ig_explanations',
        ),
        migrations.RemoveField(
            model_name='arabictopic',
            name='ig_title',
        ),
        migrations.RemoveField(
            model_name='arabictopic',
            name='yo_explanations',
        ),
        migrations.RemoveField(
            model_name='arabictopic',
            name='yo_title',
        ),
        migrations.RemoveField(
            model_name='englishtopic',
            name='ar_explanations',
        ),
        migrations.RemoveField(
            model_name='englishtopic',
            name='ar_title',
        ),
        migrations.RemoveField(
            model_name='englishtopic',
            name='en_explanations',
        ),
        migrations.RemoveField(
            model_name='englishtopic',
            name='en_title',
        ),
        migrations.RemoveField(
            model_name='englishtopic',
            name='fr_explanations',
        ),
        migrations.RemoveField(
            model_name='englishtopic',
            name='fr_title',
        ),
        migrations.RemoveField(
            model_name='englishtopic',
            name='ha_explanations',
        ),
        migrations.RemoveField(
            model_name='englishtopic',
            name='ha_title',
        ),
        migrations.RemoveField(
            model_name='englishtopic',
            name='ig_explanations',
        ),
        migrations.RemoveField(
            model_name='englishtopic',
            name='ig_title',
        ),
        migrations.RemoveField(
            model_name='englishtopic',
            name='yo_explanations',
        ),
        migrations.RemoveField(
            model_name='englishtopic',
            name='yo_title',
        ),
        migrations.RemoveField(
            model_name='frenchtopic',
            name='ar_explanations',
        ),
        migrations.RemoveField(
            model_name='frenchtopic',
            name='ar_title',
        ),
        migrations.RemoveField(
            model_name='frenchtopic',
            name='en_explanations',
        ),
        migrations.RemoveField(
            model_name='frenchtopic',
            name='en_title',
        ),
        migrations.RemoveField(
            model_name='frenchtopic',
            name='fr_explanations',
        ),
        migrations.RemoveField(
            model_name='frenchtopic',
            name='fr_title',
        ),
        migrations.RemoveField(
            model_name='frenchtopic',
            name='ha_explanations',
        ),
        migrations.RemoveField(
            model_name='frenchtopic',
            name='ha_title',
        ),
        migrations.RemoveField(
            model_name='frenchtopic',
            name='ig_explanations',
        ),
        migrations.RemoveField(
            model_name='frenchtopic',
            name='ig_title',
        ),
        migrations.RemoveField(
            model_name='frenchtopic',
            name='yo_explanations',
        ),
        migrations.RemoveField(
            model_name='frenchtopic',
            name='yo_title',
        ),
        migrations.RemoveField(
            model_name='hausatopic',
            name='ar_explanations',
        ),
        migrations.RemoveField(
            model_name='hausatopic',
            name='ar_title',
        ),
        migrations.RemoveField(
            model_name='hausatopic',
            name='en_explanations',
        ),
        migrations.RemoveField(
            model_name='hausatopic',
            name='en_title',
        ),
        migrations.RemoveField(
            model_name='hausatopic',
            name='fr_explanations',
        ),
        migrations.RemoveField(
            model_name='hausatopic',
            name='fr_title',
        ),
        migrations.RemoveField(
            model_name='hausatopic',
            name='ha_explanations',
        ),
        migrations.RemoveField(
            model_name='hausatopic',
            name='ha_title',
        ),
        migrations.RemoveField(
            model_name='hausatopic',
            name='ig_explanations',
        ),
        migrations.RemoveField(
            model_name='hausatopic',
            name='ig_title',
        ),
        migrations.RemoveField(
            model_name='hausatopic',
            name='yo_explanations',
        ),
        migrations.RemoveField(
            model_name='hausatopic',
            name='yo_title',
        ),
        migrations.RemoveField(
            model_name='igbotopic',
            name='ar_explanations',
        ),
        migrations.RemoveField(
            model_name='igbotopic',
            name='ar_title',
        ),
        migrations.RemoveField(
            model_name='igbotopic',
            name='en_explanations',
        ),
        migrations.RemoveField(
            model_name='igbotopic',
            name='en_title',
        ),
        migrations.RemoveField(
            model_name='igbotopic',
            name='fr_explanations',
        ),
        migrations.RemoveField(
            model_name='igbotopic',
            name='fr_title',
        ),
        migrations.RemoveField(
            model_name='igbotopic',
            name='ha_explanations',
        ),
        migrations.RemoveField(
            model_name='igbotopic',
            name='ha_title',
        ),
        migrations.RemoveField(
            model_name='igbotopic',
            name='ig_explanations',
        ),
        migrations.RemoveField(
            model_name='igbotopic',
            name='ig_title',
        ),
        migrations.RemoveField(
            model_name='igbotopic',
            name='yo_explanations',
        ),
        migrations.RemoveField(
            model_name='igbotopic',
            name='yo_title',
        ),
        migrations.RemoveField(
            model_name='yorubatopic',
            name='ar_explanations',
        ),
        migrations.RemoveField(
            model_name='yorubatopic',
            name='ar_title',
        ),
        migrations.RemoveField(
            model_name='yorubatopic',
            name='en_explanations',
        ),
        migrations.RemoveField(
            model_name='yorubatopic',
            name='en_title',
        ),
        migrations.RemoveField(
            model_name='yorubatopic',
            name='fr_explanations',
        ),
        migrations.RemoveField(
            model_name='yorubatopic',
            name='fr_title',
        ),
        migrations.RemoveField(
            model_name='yorubatopic',
            name='ha_explanations',
        ),
        migrations.RemoveField(
            model_name='yorubatopic',
            name='ha_title',
        ),
        migrations.RemoveField(
            model_name='yorubatopic',
            name='ig_explanations',
        ),
        migrations.RemoveField(
            model_name='yorubatopic',
            name='ig_title',
        ),
        migrations.RemoveField(
            model_name='yorubatopic',
            name='yo_explanations',
        ),
        migrations.RemoveField(
            model_name='yorubatopic',
            name='yo_title',
        ),
        migrations.AddField(
            model_name='arabictopic',
            name='AR_explanations',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='arabictopic',
            name='AR_title',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='arabictopic',
            name='EN_explanations',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='arabictopic',
            name='EN_title',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='arabictopic',
            name='FR_explanations',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='arabictopic',
            name='FR_title',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='arabictopic',
            name='HA_explanations',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='arabictopic',
            name='HA_title',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='arabictopic',
            name='IG_explanations',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='arabictopic',
            name='IG_title',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='arabictopic',
            name='YO_explanations',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='arabictopic',
            name='YO_title',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='arabictopic',
            name='published',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='arabictopic',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='englishtopic',
            name='AR_explanations',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='englishtopic',
            name='AR_title',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='englishtopic',
            name='EN_explanations',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='englishtopic',
            name='EN_title',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='englishtopic',
            name='FR_explanations',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='englishtopic',
            name='FR_title',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='englishtopic',
            name='HA_explanations',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='englishtopic',
            name='HA_title',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='englishtopic',
            name='IG_explanations',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='englishtopic',
            name='IG_title',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='englishtopic',
            name='YO_explanations',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='englishtopic',
            name='YO_title',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='englishtopic',
            name='published',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='englishtopic',
            name='read',
            field=models.ManyToManyField(blank=True, related_name='EN_posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='englishtopic',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='frenchtopic',
            name='AR_explanations',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='frenchtopic',
            name='AR_title',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='frenchtopic',
            name='EN_explanations',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='frenchtopic',
            name='EN_title',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='frenchtopic',
            name='FR_explanations',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='frenchtopic',
            name='FR_title',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='frenchtopic',
            name='HA_explanations',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='frenchtopic',
            name='HA_title',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='frenchtopic',
            name='IG_explanations',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='frenchtopic',
            name='IG_title',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='frenchtopic',
            name='YO_explanations',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='frenchtopic',
            name='YO_title',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='frenchtopic',
            name='published',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='frenchtopic',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='hausatopic',
            name='AR_explanations',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='hausatopic',
            name='AR_title',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='hausatopic',
            name='EN_explanations',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='hausatopic',
            name='EN_title',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='hausatopic',
            name='FR_explanations',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='hausatopic',
            name='FR_title',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='hausatopic',
            name='HA_explanations',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='hausatopic',
            name='HA_title',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='hausatopic',
            name='IG_explanations',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='hausatopic',
            name='IG_title',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='hausatopic',
            name='YO_explanations',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='hausatopic',
            name='YO_title',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='hausatopic',
            name='published',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='hausatopic',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='igbotopic',
            name='AR_explanations',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='igbotopic',
            name='AR_title',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='igbotopic',
            name='EN_explanations',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='igbotopic',
            name='EN_title',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='igbotopic',
            name='FR_explanations',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='igbotopic',
            name='FR_title',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='igbotopic',
            name='HA_explanations',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='igbotopic',
            name='HA_title',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='igbotopic',
            name='IG_explanations',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='igbotopic',
            name='IG_title',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='igbotopic',
            name='YO_explanations',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='igbotopic',
            name='YO_title',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='igbotopic',
            name='published',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='igbotopic',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='yorubatopic',
            name='AR_explanations',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='yorubatopic',
            name='AR_title',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='yorubatopic',
            name='EN_explanations',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='yorubatopic',
            name='EN_title',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='yorubatopic',
            name='FR_explanations',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='yorubatopic',
            name='FR_title',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='yorubatopic',
            name='HA_explanations',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='yorubatopic',
            name='HA_title',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='yorubatopic',
            name='IG_explanations',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='yorubatopic',
            name='IG_title',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='yorubatopic',
            name='YO_explanations',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='yorubatopic',
            name='YO_title',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='yorubatopic',
            name='published',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='yorubatopic',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='arabictopic',
            name='Arabic_explanations',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='arabictopic',
            name='Arabic_title',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, max_length=255, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='category',
            name='title',
            field=ckeditor_uploader.fields.RichTextUploadingField(max_length=75, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='englishtopic',
            name='English_explanations',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='englishtopic',
            name='English_title',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='frenchtopic',
            name='French_explanations',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='frenchtopic',
            name='French_title',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='hausatopic',
            name='Hausa_explanations',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='hausatopic',
            name='Hausa_title',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='igbotopic',
            name='Igbo_explanations',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='igbotopic',
            name='Igbo_title',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='yorubatopic',
            name='Yoruba_explanations',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='yorubatopic',
            name='Yoruba_title',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='ENReadCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='EN_posts', to='Alteernlingual_topic.englishtopic')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
