# Generated by Django 3.2.5 on 2022-03-12 08:58

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Alteernlingual_topic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='title')),
                ('description', models.TextField(blank=True, max_length=255, verbose_name='description')),
            ],
        ),
        migrations.CreateModel(
            name='LanguageFollow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='language_follow', to='Alteernlingual_topic.language', verbose_name='language')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LanguageLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('language', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='Alteernlingual_topic.language')),
            ],
        ),
        migrations.CreateModel(
            name='LanguageOfInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loi', models.CharField(default=False, max_length=60, null=True)),
                ('num', models.IntegerField(default=False, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LevelFollow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='level_follow', to='Alteernlingual_topic.languagelevel', verbose_name='level')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LoiFollow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loi_follow', to='Alteernlingual_topic.languageofinteraction', verbose_name='loi')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='readCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Alteernlingual_topic.language', verbose_name='language')),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='title')),
                ('main_title', models.TextField(blank=True, default=None, max_length=50000, null=True)),
                ('main_explanations', ckeditor_uploader.fields.RichTextUploadingField(blank=True, default=None, null=True)),
                ('AR_title', models.TextField(blank=True, default=None, max_length=50000, null=True)),
                ('AR_explanations', models.TextField(blank=True, default=None, null=True)),
                ('EN_title', models.TextField(blank=True, default=None, max_length=50000, null=True)),
                ('EN_explanations', ckeditor_uploader.fields.RichTextUploadingField(blank=True, default=None, null=True)),
                ('FR_title', models.TextField(blank=True, default=None, max_length=50000, null=True)),
                ('FR_explanations', models.TextField(blank=True, default=None, null=True)),
                ('HA_title', models.TextField(blank=True, default=None, max_length=50000, null=True)),
                ('HA_explanations', models.TextField(blank=True, default=None, null=True)),
                ('IG_title', models.TextField(blank=True, default=None, max_length=50000, null=True)),
                ('IG_explanations', models.TextField(blank=True, default=None, null=True)),
                ('YO_title', models.TextField(blank=True, default=None, max_length=50000, null=True)),
                ('YO_explanations', ckeditor_uploader.fields.RichTextUploadingField(blank=True, default=None, null=True)),
                ('published', models.DateField(auto_now_add=True, null=True)),
                ('slug', models.SlugField(blank=True, max_length=50000, null=True, unique=True)),
                ('language', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='follow_language', to='Alteernlingual_topic.language', verbose_name='topic_language')),
                ('level', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Alteernlingual_topic.languagelevel', verbose_name='level')),
                ('read', models.ManyToManyField(blank=True, related_name='read', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='englishtopic',
            name='category',
        ),
        migrations.RemoveField(
            model_name='frenchtopic',
            name='category',
        ),
        migrations.RemoveField(
            model_name='hausatopic',
            name='category',
        ),
        migrations.RemoveField(
            model_name='igbotopic',
            name='category',
        ),
        migrations.RemoveField(
            model_name='yorubatopic',
            name='category',
        ),
        migrations.DeleteModel(
            name='ArabicTopic',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='EnglishTopic',
        ),
        migrations.DeleteModel(
            name='FrenchTopic',
        ),
        migrations.DeleteModel(
            name='HausaTopic',
        ),
        migrations.DeleteModel(
            name='IgboTopic',
        ),
        migrations.DeleteModel(
            name='YorubaTopic',
        ),
        migrations.AddField(
            model_name='readcount',
            name='read',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='read_topics', to='Alteernlingual_topic.topic'),
        ),
        migrations.AddField(
            model_name='readcount',
            name='subtopic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Alteernlingual_topic.topic'),
        ),
        migrations.AddField(
            model_name='readcount',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
