# Generated by Django 3.2.5 on 2023-01-01 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Alteernlingual_topic', '0002_auto_20220312_0958'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='AR_explanations',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='AR_title',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='EN_title',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='FR_explanations',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='FR_title',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='HA_explanations',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='HA_title',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='IG_explanations',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='IG_title',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='YO_explanations',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='YO_title',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='language',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='level',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='main_title',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='published',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='read',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='slug',
        ),
    ]
