# Generated by Django 3.2.5 on 2021-08-22 20:03

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alteernlingual_topic', '0002_auto_20210822_2051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arabictopic',
            name='AR_title',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default=None, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='arabictopic',
            name='Arabic_title',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default=None, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='arabictopic',
            name='EN_title',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default=None, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='arabictopic',
            name='FR_title',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default=None, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='arabictopic',
            name='HA_title',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default=None, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='arabictopic',
            name='IG_title',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default=None, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='arabictopic',
            name='YO_title',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default=None, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='arabictopic',
            name='slug',
            field=models.SlugField(blank=True, max_length=250, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, max_length=255, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(max_length=75, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='englishtopic',
            name='AR_title',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default=None, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='englishtopic',
            name='EN_title',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default=None, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='englishtopic',
            name='English_title',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default=None, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='englishtopic',
            name='FR_title',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default=None, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='englishtopic',
            name='HA_title',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default=None, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='englishtopic',
            name='IG_title',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default=None, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='englishtopic',
            name='YO_title',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default=None, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='englishtopic',
            name='slug',
            field=models.SlugField(blank=True, max_length=250, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='frenchtopic',
            name='AR_title',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default=None, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='frenchtopic',
            name='EN_title',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default=None, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='frenchtopic',
            name='FR_title',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default=None, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='frenchtopic',
            name='French_title',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default=None, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='frenchtopic',
            name='HA_title',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default=None, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='frenchtopic',
            name='IG_title',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default=None, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='frenchtopic',
            name='YO_title',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default=None, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='frenchtopic',
            name='slug',
            field=models.SlugField(blank=True, max_length=250, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='hausatopic',
            name='AR_title',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default=None, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='hausatopic',
            name='EN_title',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default=None, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='hausatopic',
            name='FR_title',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default=None, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='hausatopic',
            name='HA_title',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default=None, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='hausatopic',
            name='Hausa_title',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default=None, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='hausatopic',
            name='IG_title',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default=None, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='hausatopic',
            name='YO_title',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default=None, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='hausatopic',
            name='slug',
            field=models.SlugField(blank=True, max_length=250, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='igbotopic',
            name='AR_title',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default=None, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='igbotopic',
            name='EN_title',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default=None, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='igbotopic',
            name='FR_title',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default=None, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='igbotopic',
            name='HA_title',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default=None, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='igbotopic',
            name='IG_title',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default=None, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='igbotopic',
            name='Igbo_title',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default=None, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='igbotopic',
            name='YO_title',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default=None, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='igbotopic',
            name='slug',
            field=models.SlugField(blank=True, max_length=250, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='yorubatopic',
            name='AR_title',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default=None, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='yorubatopic',
            name='EN_title',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default=None, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='yorubatopic',
            name='FR_title',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default=None, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='yorubatopic',
            name='HA_title',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default=None, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='yorubatopic',
            name='IG_title',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default=None, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='yorubatopic',
            name='YO_title',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default=None, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='yorubatopic',
            name='Yoruba_title',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default=None, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='yorubatopic',
            name='slug',
            field=models.SlugField(blank=True, max_length=250, null=True, unique=True),
        ),
    ]
