# Generated by Django 3.2.5 on 2023-01-17 15:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Alteernlingual_topic', '0003_remove_topic_read_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='read_by',
            field=models.ManyToManyField(blank=True, related_name='read_topics', to=settings.AUTH_USER_MODEL),
        ),
    ]
