# Generated by Django 3.2.5 on 2023-01-17 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Alteernlingual_topic', '0004_topic_read_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='read_by',
        ),
    ]
