# Generated by Django 3.2.5 on 2021-09-15 01:28

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Alteernlingual_topic', '0005_auto_20210823_2255'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='title')),
                ('description', models.TextField(blank=True, max_length=255, verbose_name='description')),
            ],
        ),
        migrations.CreateModel(
            name='LanguageFollow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='language_follow', to='Alteernlingual_topic.language', verbose_name='language')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Loi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loi', models.CharField(default=False, max_length=60, null=True)),
                ('num', models.IntegerField(default=False, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LoiFollow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loi_follow', to='Alteernlingual_topic.loi', verbose_name='loi')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('language', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='Alteernlingual_topic.language')),
            ],
        ),
        migrations.CreateModel(
            name='SkillFollow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_follow', to='Alteernlingual_topic.skill', verbose_name='skill')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SubTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='title')),
                ('English_title', ckeditor_uploader.fields.RichTextUploadingField(blank=True, default=None, max_length=50000, null=True)),
                ('English_explanations', ckeditor_uploader.fields.RichTextUploadingField(blank=True, default=None, null=True)),
                ('EN_title', ckeditor_uploader.fields.RichTextUploadingField(blank=True, default=None, max_length=50000, null=True)),
                ('EN_explanations', ckeditor_uploader.fields.RichTextUploadingField(blank=True, default=None, null=True)),
                ('IG_title', ckeditor_uploader.fields.RichTextUploadingField(blank=True, default=None, max_length=50000, null=True)),
                ('IG_explanations', ckeditor_uploader.fields.RichTextUploadingField(blank=True, default=None, null=True)),
                ('HA_title', ckeditor_uploader.fields.RichTextUploadingField(blank=True, default=None, max_length=50000, null=True)),
                ('HA_explanations', ckeditor_uploader.fields.RichTextUploadingField(blank=True, default=None, null=True)),
                ('YO_title', ckeditor_uploader.fields.RichTextUploadingField(blank=True, default=None, max_length=50000, null=True)),
                ('YO_explanations', ckeditor_uploader.fields.RichTextUploadingField(blank=True, default=None, null=True)),
                ('FR_title', ckeditor_uploader.fields.RichTextUploadingField(blank=True, default=None, max_length=50000, null=True)),
                ('FR_explanations', ckeditor_uploader.fields.RichTextUploadingField(blank=True, default=None, null=True)),
                ('AR_title', ckeditor_uploader.fields.RichTextUploadingField(blank=True, default=None, max_length=50000, null=True)),
                ('AR_explanations', ckeditor_uploader.fields.RichTextUploadingField(blank=True, default=None, null=True)),
                ('published', models.DateField(auto_now_add=True, null=True)),
                ('slug', models.SlugField(blank=True, max_length=50000, null=True, unique=True)),
                ('language', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Alteernlingual_topic.language', verbose_name='language')),
                ('read', models.ManyToManyField(blank=True, related_name='EN_posts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('skill', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='Alteernlingual_topic.skill')),
            ],
        ),
        migrations.RemoveField(
            model_name='arreadcount',
            name='read',
        ),
        migrations.RemoveField(
            model_name='arreadcount',
            name='user',
        ),
        migrations.RemoveField(
            model_name='englishtopic',
            name='category',
        ),
        migrations.RemoveField(
            model_name='englishtopic',
            name='read',
        ),
        migrations.RemoveField(
            model_name='enreadcount',
            name='read',
        ),
        migrations.RemoveField(
            model_name='enreadcount',
            name='user',
        ),
        migrations.RemoveField(
            model_name='frenchtopic',
            name='category',
        ),
        migrations.RemoveField(
            model_name='frenchtopic',
            name='read',
        ),
        migrations.RemoveField(
            model_name='frreadcount',
            name='read',
        ),
        migrations.RemoveField(
            model_name='frreadcount',
            name='user',
        ),
        migrations.RemoveField(
            model_name='hareadcount',
            name='read',
        ),
        migrations.RemoveField(
            model_name='hareadcount',
            name='user',
        ),
        migrations.RemoveField(
            model_name='hausatopic',
            name='category',
        ),
        migrations.RemoveField(
            model_name='hausatopic',
            name='read',
        ),
        migrations.RemoveField(
            model_name='igbotopic',
            name='category',
        ),
        migrations.RemoveField(
            model_name='igbotopic',
            name='read',
        ),
        migrations.RemoveField(
            model_name='igreadcount',
            name='read',
        ),
        migrations.RemoveField(
            model_name='igreadcount',
            name='user',
        ),
        migrations.RemoveField(
            model_name='yoreadcount',
            name='read',
        ),
        migrations.RemoveField(
            model_name='yoreadcount',
            name='user',
        ),
        migrations.RemoveField(
            model_name='yorubatopic',
            name='category',
        ),
        migrations.RemoveField(
            model_name='yorubatopic',
            name='read',
        ),
        migrations.DeleteModel(
            name='ArabicTopic',
        ),
        migrations.DeleteModel(
            name='ARReadCount',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='EnglishTopic',
        ),
        migrations.DeleteModel(
            name='ENReadCount',
        ),
        migrations.DeleteModel(
            name='FrenchTopic',
        ),
        migrations.DeleteModel(
            name='FRReadCount',
        ),
        migrations.DeleteModel(
            name='HAReadCount',
        ),
        migrations.DeleteModel(
            name='HausaTopic',
        ),
        migrations.DeleteModel(
            name='IgboTopic',
        ),
        migrations.DeleteModel(
            name='IGReadCount',
        ),
        migrations.DeleteModel(
            name='YOReadCount',
        ),
        migrations.DeleteModel(
            name='YorubaTopic',
        ),
        migrations.AddField(
            model_name='subtopic',
            name='topic',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Alteernlingual_topic.topic', verbose_name='topic'),
        ),
    ]
