# Generated by Django 3.2.5 on 2021-09-15 02:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Alteernlingual_topic', '0006_auto_20210915_0228'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subtopic',
            old_name='English_explanations',
            new_name='main_explanations',
        ),
        migrations.RenameField(
            model_name='subtopic',
            old_name='English_title',
            new_name='main_title',
        ),
    ]
