# Generated by Django 3.2.5 on 2023-01-17 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alteernlingual_topic', '0006_auto_20230117_0807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='title',
            field=models.CharField(max_length=150, verbose_name='title'),
        ),
    ]
