# Generated by Django 3.2.5 on 2021-09-18 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alteernlingual_topic', '0009_subtopicdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtopicdetails',
            name='title',
            field=models.CharField(blank=True, default=None, max_length=150, verbose_name='title'),
        ),
    ]
