# Generated by Django 3.2.5 on 2021-09-18 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Alteernlingual_topic', '0010_subtopicdetails_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subtopicdetails',
            name='title',
        ),
    ]
