# Generated by Django 3.2.5 on 2021-09-19 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Alteernlingual_topic', '0012_subtopicdetails_title'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Loi',
            new_name='LanguageOfInteraction',
        ),
    ]
