# Generated by Django 3.2.5 on 2021-09-21 14:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Alteernlingual_topic', '0013_rename_loi_languageofinteraction'),
    ]

    operations = [
        migrations.AddField(
            model_name='readcount',
            name='language',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Alteernlingual_topic.language', verbose_name='language'),
        ),
        migrations.AlterField(
            model_name='subtopic',
            name='language',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Alteernlingual_topic.language', verbose_name='topic_language'),
        ),
        migrations.AlterField(
            model_name='subtopic',
            name='read',
            field=models.ManyToManyField(blank=True, related_name='read', to=settings.AUTH_USER_MODEL),
        ),
    ]
