# Generated by Django 3.2.5 on 2021-09-21 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Alteernlingual_topic', '0015_readcount_subtopic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='readcount',
            old_name='SubTopic',
            new_name='subtopic',
        ),
    ]
