# Generated by Django 3.2.5 on 2021-09-21 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Alteernlingual_topic', '0016_rename_subtopic_readcount_subtopic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subtopic',
            name='AR_explanations',
        ),
        migrations.RemoveField(
            model_name='subtopic',
            name='EN_explanations',
        ),
        migrations.RemoveField(
            model_name='subtopic',
            name='FR_explanations',
        ),
        migrations.RemoveField(
            model_name='subtopic',
            name='HA_explanations',
        ),
        migrations.RemoveField(
            model_name='subtopic',
            name='IG_explanations',
        ),
        migrations.RemoveField(
            model_name='subtopic',
            name='YO_explanations',
        ),
    ]
