# Generated by Django 3.2.5 on 2021-09-27 07:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Alteernlingual_topic', '0017_auto_20210921_2048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtopic',
            name='language',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='follow_language', to='Alteernlingual_topic.language', verbose_name='topic_language'),
        ),
        migrations.CreateModel(
            name='SubTopicFollow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtopic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtopic_follow', to='Alteernlingual_topic.subtopic', verbose_name='subtopic')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
