# Generated by Django 3.2.5 on 2021-09-27 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Alteernlingual_topic', '0018_auto_20210927_0859'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtopicfollow',
            name='language',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Alteernlingual_topic.language', verbose_name='language'),
        ),
    ]
