# Generated by Django 3.2.5 on 2021-09-27 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Alteernlingual_topic', '0021_subtopicfollow_language'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subtopicfollow',
            name='language',
        ),
    ]
