# Generated by Django 3.2.5 on 2021-09-27 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Alteernlingual_topic', '0022_remove_subtopicfollow_language'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SubTopicFollow',
        ),
    ]
