# Generated by Django 3.2.5 on 2021-09-28 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alteernlingual_topic', '0025_alter_subtopicdetails_audio_file_ig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtopicdetails',
            name='audio_file_ig',
            field=models.FileField(blank=True, default=None, null=True, upload_to='audios_ig/'),
        ),
    ]
