# Generated by Django 3.2.5 on 2021-09-28 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alteernlingual_topic', '0027_auto_20210928_2039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtopicdetails',
            name='audio_file_ar',
            field=models.FileField(blank=True, default=None, null=True, upload_to='audios_ar/'),
        ),
        migrations.AlterField(
            model_name='subtopicdetails',
            name='audio_file_en',
            field=models.FileField(blank=True, default=None, null=True, upload_to='audios_en/'),
        ),
        migrations.AlterField(
            model_name='subtopicdetails',
            name='audio_file_fr',
            field=models.FileField(blank=True, default=None, null=True, upload_to='audios_fr/'),
        ),
        migrations.AlterField(
            model_name='subtopicdetails',
            name='audio_file_ha',
            field=models.FileField(blank=True, default=None, null=True, upload_to='audios_ha/'),
        ),
        migrations.AlterField(
            model_name='subtopicdetails',
            name='audio_file_ig',
            field=models.FileField(blank=True, default=None, null=True, upload_to='audios_ig/'),
        ),
        migrations.AlterField(
            model_name='subtopicdetails',
            name='audio_file_yo',
            field=models.FileField(blank=True, default=None, null=True, upload_to='audios_yo/'),
        ),
        migrations.AlterField(
            model_name='subtopicdetails',
            name='audio_main',
            field=models.FileField(blank=True, default=None, null=True, upload_to='audios/'),
        ),
    ]
