# Generated by Django 3.2.5 on 2021-09-29 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alteernlingual_topic', '0028_auto_20210928_2052'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subtopicdetails',
            old_name='audio_file_ar',
            new_name='audio_file_ar1',
        ),
        migrations.RenameField(
            model_name='subtopicdetails',
            old_name='audio_file_en',
            new_name='audio_file_en1',
        ),
        migrations.RenameField(
            model_name='subtopicdetails',
            old_name='audio_file_fr',
            new_name='audio_file_fr1',
        ),
        migrations.RenameField(
            model_name='subtopicdetails',
            old_name='audio_file_ha',
            new_name='audio_file_ha1',
        ),
        migrations.RenameField(
            model_name='subtopicdetails',
            old_name='audio_file_yo',
            new_name='audio_file_yo1',
        ),
        migrations.RenameField(
            model_name='subtopicdetails',
            old_name='audio_main',
            new_name='audio_main1',
        ),
        migrations.RemoveField(
            model_name='subtopicdetails',
            name='AR_explanations',
        ),
        migrations.RemoveField(
            model_name='subtopicdetails',
            name='EN_explanations',
        ),
        migrations.RemoveField(
            model_name='subtopicdetails',
            name='FR_explanations',
        ),
        migrations.RemoveField(
            model_name='subtopicdetails',
            name='HA_explanations',
        ),
        migrations.RemoveField(
            model_name='subtopicdetails',
            name='IG_explanations',
        ),
        migrations.RemoveField(
            model_name='subtopicdetails',
            name='YO_explanations',
        ),
        migrations.RemoveField(
            model_name='subtopicdetails',
            name='main_explanations',
        ),
        migrations.AddField(
            model_name='subtopicdetails',
            name='AR_explanations1',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='subtopicdetails',
            name='AR_explanations2',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='subtopicdetails',
            name='AR_explanations3',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='subtopicdetails',
            name='AR_explanations4',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='subtopicdetails',
            name='AR_explanations5',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='subtopicdetails',
            name='AR_explanations6',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='subtopicdetails',
            name='AR_explanations7',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='subtopicdetails',
            name='EN_explanations1',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='subtopicdetails',
            name='EN_explanations2',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='subtopicdetails',
            name='EN_explanations3',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='subtopicdetails',
            name='EN_explanations4',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='subtopicdetails',
            name='EN_explanations5',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='subtopicdetails',
            name='EN_explanations6',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='subtopicdetails',
            name='EN_explanations7',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='subtopicdetails',
            name='FR_explanations1',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='subtopicdetails',
            name='FR_explanations2',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='subtopicdetails',
            name='FR_explanations3',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='subtopicdetails',
            name='FR_explanations4',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='subtopicdetails',
            name='FR_explanations5',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='subtopicdetails',
            name='FR_explanations6',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='subtopicdetails',
            name='FR_explanations7',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='subtopicdetails',
            name='HA_explanations1',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='subtopicdetails',
            name='HA_explanations2',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='subtopicdetails',
            name='HA_explanations3',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='subtopicdetails',
            name='HA_explanations4',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='subtopicdetails',
            name='HA_explanations5',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='subtopicdetails',
            name='HA_explanations6',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='subtopicdetails',
            name='HA_explanations7',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='subtopicdetails',
            name='IG_explanations1',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='subtopicdetails',
            name='IG_explanations2',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='subtopicdetails',
            name='IG_explanations3',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='subtopicdetails',
            name='IG_explanations4',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='subtopicdetails',
            name='IG_explanations5',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='subtopicdetails',
            name='IG_explanations6',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='subtopicdetails',
            name='IG_explanations7',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='subtopicdetails',
            name='YO_explanations1',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='subtopicdetails',
            name='YO_explanations2',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='subtopicdetails',
            name='YO_explanations3',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='subtopicdetails',
            name='YO_explanations4',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='subtopicdetails',
            name='YO_explanations5',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='subtopicdetails',
            name='YO_explanations6',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='subtopicdetails',
            name='YO_explanations7',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='subtopicdetails',
            name='audio_file_ar2',
            field=models.FileField(blank=True, default=None, null=True, upload_to='audios_ar/'),
        ),
        migrations.AddField(
            model_name='subtopicdetails',
            name='audio_file_ar3',
            field=models.FileField(blank=True, default=None, null=True, upload_to='audios_ar/'),
        ),
        migrations.AddField(
            model_name='subtopicdetails',
            name='audio_file_ar4',
            field=models.FileField(blank=True, default=None, null=True, upload_to='audios_ar/'),
        ),
        migrations.AddField(
            model_name='subtopicdetails',
            name='audio_file_ar5',
            field=models.FileField(blank=True, default=None, null=True, upload_to='audios_ar/'),
        ),
        migrations.AddField(
            model_name='subtopicdetails',
            name='audio_file_ar6',
            field=models.FileField(blank=True, default=None, null=True, upload_to='audios_ar/'),
        ),
        migrations.AddField(
            model_name='subtopicdetails',
            name='audio_file_ar7',
            field=models.FileField(blank=True, default=None, null=True, upload_to='audios_ar/'),
        ),
        migrations.AddField(
            model_name='subtopicdetails',
            name='audio_file_en2',
            field=models.FileField(blank=True, default=None, null=True, upload_to='audios_en/'),
        ),
        migrations.AddField(
            model_name='subtopicdetails',
            name='audio_file_en3',
            field=models.FileField(blank=True, default=None, null=True, upload_to='audios_en/'),
        ),
        migrations.AddField(
            model_name='subtopicdetails',
            name='audio_file_en4',
            field=models.FileField(blank=True, default=None, null=True, upload_to='audios_en/'),
        ),
        migrations.AddField(
            model_name='subtopicdetails',
            name='audio_file_en5',
            field=models.FileField(blank=True, default=None, null=True, upload_to='audios_en/'),
        ),
        migrations.AddField(
            model_name='subtopicdetails',
            name='audio_file_en6',
            field=models.FileField(blank=True, default=None, null=True, upload_to='audios_en/'),
        ),
        migrations.AddField(
            model_name='subtopicdetails',
            name='audio_file_en7',
            field=models.FileField(blank=True, default=None, null=True, upload_to='audios_en/'),
        ),
        migrations.AddField(
            model_name='subtopicdetails',
            name='audio_file_fr2',
            field=models.FileField(blank=True, default=None, null=True, upload_to='audios_fr/'),
        ),
        migrations.AddField(
            model_name='subtopicdetails',
            name='audio_file_fr3',
            field=models.FileField(blank=True, default=None, null=True, upload_to='audios_fr/'),
        ),
        migrations.AddField(
            model_name='subtopicdetails',
            name='audio_file_fr4',
            field=models.FileField(blank=True, default=None, null=True, upload_to='audios_fr/'),
        ),
        migrations.AddField(
            model_name='subtopicdetails',
            name='audio_file_fr5',
            field=models.FileField(blank=True, default=None, null=True, upload_to='audios_fr/'),
        ),
        migrations.AddField(
            model_name='subtopicdetails',
            name='audio_file_fr6',
            field=models.FileField(blank=True, default=None, null=True, upload_to='audios_fr/'),
        ),
        migrations.AddField(
            model_name='subtopicdetails',
            name='audio_file_fr7',
            field=models.FileField(blank=True, default=None, null=True, upload_to='audios_fr/'),
        ),
        migrations.AddField(
            model_name='subtopicdetails',
            name='audio_file_ha2',
            field=models.FileField(blank=True, default=None, null=True, upload_to='audios_ha/'),
        ),
        migrations.AddField(
            model_name='subtopicdetails',
            name='audio_file_ha3',
            field=models.FileField(blank=True, default=None, null=True, upload_to='audios_ha/'),
        ),
        migrations.AddField(
            model_name='subtopicdetails',
            name='audio_file_ha4',
            field=models.FileField(blank=True, default=None, null=True, upload_to='audios_ha/'),
        ),
        migrations.AddField(
            model_name='subtopicdetails',
            name='audio_file_ha5',
            field=models.FileField(blank=True, default=None, null=True, upload_to='audios_ha/'),
        ),
        migrations.AddField(
            model_name='subtopicdetails',
            name='audio_file_ha6',
            field=models.FileField(blank=True, default=None, null=True, upload_to='audios_ha/'),
        ),
        migrations.AddField(
            model_name='subtopicdetails',
            name='audio_file_ha7',
            field=models.FileField(blank=True, default=None, null=True, upload_to='audios_ha/'),
        ),
        migrations.AddField(
            model_name='subtopicdetails',
            name='audio_file_ig1',
            field=models.FileField(blank=True, default=None, null=True, upload_to='audios_ig/'),
        ),
        migrations.AddField(
            model_name='subtopicdetails',
            name='audio_file_ig2',
            field=models.FileField(blank=True, default=None, null=True, upload_to='audios_ig/'),
        ),
        migrations.AddField(
            model_name='subtopicdetails',
            name='audio_file_ig3',
            field=models.FileField(blank=True, default=None, null=True, upload_to='audios_ig/'),
        ),
        migrations.AddField(
            model_name='subtopicdetails',
            name='audio_file_ig4',
            field=models.FileField(blank=True, default=None, null=True, upload_to='audios_ig/'),
        ),
        migrations.AddField(
            model_name='subtopicdetails',
            name='audio_file_ig5',
            field=models.FileField(blank=True, default=None, null=True, upload_to='audios_ig/'),
        ),
        migrations.AddField(
            model_name='subtopicdetails',
            name='audio_file_ig6',
            field=models.FileField(blank=True, default=None, null=True, upload_to='audios_ig/'),
        ),
        migrations.AddField(
            model_name='subtopicdetails',
            name='audio_file_yo2',
            field=models.FileField(blank=True, default=None, null=True, upload_to='audios_yo/'),
        ),
        migrations.AddField(
            model_name='subtopicdetails',
            name='audio_file_yo3',
            field=models.FileField(blank=True, default=None, null=True, upload_to='audios_yo/'),
        ),
        migrations.AddField(
            model_name='subtopicdetails',
            name='audio_file_yo4',
            field=models.FileField(blank=True, default=None, null=True, upload_to='audios_yo/'),
        ),
        migrations.AddField(
            model_name='subtopicdetails',
            name='audio_file_yo5',
            field=models.FileField(blank=True, default=None, null=True, upload_to='audios_yo/'),
        ),
        migrations.AddField(
            model_name='subtopicdetails',
            name='audio_file_yo6',
            field=models.FileField(blank=True, default=None, null=True, upload_to='audios_yo/'),
        ),
        migrations.AddField(
            model_name='subtopicdetails',
            name='audio_file_yo7',
            field=models.FileField(blank=True, default=None, null=True, upload_to='audios_yo/'),
        ),
        migrations.AddField(
            model_name='subtopicdetails',
            name='audio_main3',
            field=models.FileField(blank=True, default=None, null=True, upload_to='audios/'),
        ),
        migrations.AddField(
            model_name='subtopicdetails',
            name='audio_main4',
            field=models.FileField(blank=True, default=None, null=True, upload_to='audios/'),
        ),
        migrations.AddField(
            model_name='subtopicdetails',
            name='audio_main5',
            field=models.FileField(blank=True, default=None, null=True, upload_to='audios/'),
        ),
        migrations.AddField(
            model_name='subtopicdetails',
            name='audio_main6',
            field=models.FileField(blank=True, default=None, null=True, upload_to='audios/'),
        ),
        migrations.AddField(
            model_name='subtopicdetails',
            name='audio_main7',
            field=models.FileField(blank=True, default=None, null=True, upload_to='audios/'),
        ),
        migrations.AddField(
            model_name='subtopicdetails',
            name='main_explanations1',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='subtopicdetails',
            name='main_explanations2',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='subtopicdetails',
            name='main_explanations3',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='subtopicdetails',
            name='main_explanations4',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='subtopicdetails',
            name='main_explanations5',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='subtopicdetails',
            name='main_explanations6',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='subtopicdetails',
            name='main_explanations7',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
