# Generated by Django 3.2.5 on 2021-09-29 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alteernlingual_topic', '0030_auto_20210929_0954'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subtopic',
            name='main_explanations',
        ),
        migrations.AddField(
            model_name='subtopic',
            name='audio_file_ar',
            field=models.FileField(blank=True, default=None, null=True, upload_to='audios_en/'),
        ),
        migrations.AddField(
            model_name='subtopic',
            name='audio_file_en',
            field=models.FileField(blank=True, default=None, null=True, upload_to='audios_en/'),
        ),
        migrations.AddField(
            model_name='subtopic',
            name='audio_file_fr',
            field=models.FileField(blank=True, default=None, null=True, upload_to='audios_en/'),
        ),
        migrations.AddField(
            model_name='subtopic',
            name='audio_file_ha',
            field=models.FileField(blank=True, default=None, null=True, upload_to='audios_en/'),
        ),
        migrations.AddField(
            model_name='subtopic',
            name='audio_file_ig',
            field=models.FileField(blank=True, default=None, null=True, upload_to='audios_en/'),
        ),
        migrations.AddField(
            model_name='subtopic',
            name='audio_file_yo',
            field=models.FileField(blank=True, default=None, null=True, upload_to='audios_en/'),
        ),
        migrations.AddField(
            model_name='subtopic',
            name='audio_main_title',
            field=models.FileField(blank=True, default=None, null=True, upload_to='audios/'),
        ),
    ]
