# Generated by Django 3.2.5 on 2021-09-29 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alteernlingual_topic', '0031_auto_20210929_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtopic',
            name='AR_title',
            field=models.TextField(blank=True, default=None, max_length=50000, null=True),
        ),
        migrations.AlterField(
            model_name='subtopic',
            name='EN_title',
            field=models.TextField(blank=True, default=None, max_length=50000, null=True),
        ),
        migrations.AlterField(
            model_name='subtopic',
            name='FR_title',
            field=models.TextField(blank=True, default=None, max_length=50000, null=True),
        ),
        migrations.AlterField(
            model_name='subtopic',
            name='HA_title',
            field=models.TextField(blank=True, default=None, max_length=50000, null=True),
        ),
        migrations.AlterField(
            model_name='subtopic',
            name='IG_title',
            field=models.TextField(blank=True, default=None, max_length=50000, null=True),
        ),
        migrations.AlterField(
            model_name='subtopic',
            name='YO_title',
            field=models.TextField(blank=True, default=None, max_length=50000, null=True),
        ),
        migrations.AlterField(
            model_name='subtopic',
            name='main_title',
            field=models.TextField(blank=True, default=None, max_length=50000, null=True),
        ),
    ]
