# Generated by Django 3.2.5 on 2021-10-03 11:53

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Alteernlingual_topic', '0032_auto_20210929_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtopicdetails',
            name='EN_explanations',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='subtopicdetails',
            name='YO_explanations',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='subtopicdetails',
            name='main_explanations',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default=None, null=True),
        ),
    ]
