# Generated by Django 3.2.5 on 2021-09-16 07:13

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Alteernlingual_topic', '0008_readcount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='title')),
                ('description', models.TextField(blank=True, max_length=255, verbose_name='description')),
                ('language', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='Alteernlingual_topic.language')),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='title')),
                ('main_title', ckeditor_uploader.fields.RichTextUploadingField(blank=True, default=None, max_length=50000, null=True)),
                ('main_explanations', ckeditor_uploader.fields.RichTextUploadingField(blank=True, default=None, null=True)),
                ('EN_title', ckeditor_uploader.fields.RichTextUploadingField(blank=True, default=None, max_length=50000, null=True)),
                ('EN_explanations', ckeditor_uploader.fields.RichTextUploadingField(blank=True, default=None, null=True)),
                ('IG_title', ckeditor_uploader.fields.RichTextUploadingField(blank=True, default=None, max_length=50000, null=True)),
                ('IG_explanations', ckeditor_uploader.fields.RichTextUploadingField(blank=True, default=None, null=True)),
                ('HA_title', ckeditor_uploader.fields.RichTextUploadingField(blank=True, default=None, max_length=50000, null=True)),
                ('HA_explanations', ckeditor_uploader.fields.RichTextUploadingField(blank=True, default=None, null=True)),
                ('YO_title', ckeditor_uploader.fields.RichTextUploadingField(blank=True, default=None, max_length=50000, null=True)),
                ('YO_explanations', ckeditor_uploader.fields.RichTextUploadingField(blank=True, default=None, null=True)),
                ('FR_title', ckeditor_uploader.fields.RichTextUploadingField(blank=True, default=None, max_length=50000, null=True)),
                ('FR_explanations', ckeditor_uploader.fields.RichTextUploadingField(blank=True, default=None, null=True)),
                ('AR_title', ckeditor_uploader.fields.RichTextUploadingField(blank=True, default=None, max_length=50000, null=True)),
                ('AR_explanations', ckeditor_uploader.fields.RichTextUploadingField(blank=True, default=None, null=True)),
                ('published', models.DateField(auto_now_add=True, null=True)),
                ('slug', models.SlugField(blank=True, max_length=50000, null=True, unique=True)),
                ('language', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Alteernlingual_topic.language', verbose_name='language')),
                ('subject', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='alteernlingual_subjects.subject', verbose_name='subject')),
            ],
        ),
    ]
