# Generated by Django 3.2.5 on 2022-03-12 08:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='title')),
                ('description', models.TextField(blank=True, max_length=255, verbose_name='description')),
            ],
        ),
        migrations.CreateModel(
            name='SubjectSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('subject', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='alteernlingual_subjects.subject')),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='title')),
                ('main_title', models.TextField(blank=True, default=None, max_length=50000, null=True)),
                ('audio_main_title', models.FileField(blank=True, default=None, null=True, upload_to='audios/')),
                ('AR_title', models.TextField(blank=True, default=None, max_length=50000, null=True)),
                ('audio_file_ar', models.FileField(blank=True, default=None, null=True, upload_to='audios_en/')),
                ('EN_title', models.TextField(blank=True, default=None, max_length=50000, null=True)),
                ('audio_file_en', models.FileField(blank=True, default=None, null=True, upload_to='audios_en/')),
                ('FR_title', models.TextField(blank=True, default=None, max_length=50000, null=True)),
                ('audio_file_fr', models.FileField(blank=True, default=None, null=True, upload_to='audios_en/')),
                ('HA_title', models.TextField(blank=True, default=None, max_length=50000, null=True)),
                ('audio_file_ha', models.FileField(blank=True, default=None, null=True, upload_to='audios_en/')),
                ('IG_title', models.TextField(blank=True, default=None, max_length=50000, null=True)),
                ('audio_file_ig', models.FileField(blank=True, default=None, null=True, upload_to='audios_en/')),
                ('YO_title', models.TextField(blank=True, default=None, max_length=50000, null=True)),
                ('audio_file_yo', models.FileField(blank=True, default=None, null=True, upload_to='audios_en/')),
                ('published', models.DateField(auto_now_add=True, null=True)),
                ('slug', models.SlugField(blank=True, max_length=50000, null=True, unique=True)),
                ('read', models.ManyToManyField(blank=True, related_name='readsubject', to=settings.AUTH_USER_MODEL)),
                ('skill', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='alteernlingual_subjects.subjectskill', verbose_name='subject_skill')),
                ('subject', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='alteernlingual_subjects.subject', verbose_name='subject')),
            ],
        ),
        migrations.CreateModel(
            name='TopicContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default=None, max_length=150, verbose_name='title')),
                ('main_explanations', models.TextField(blank=True, default=None, null=True)),
                ('audio_main', models.FileField(blank=True, default=None, null=True, upload_to='audios/')),
                ('AR_explanations', models.TextField(blank=True, default=None, null=True)),
                ('audio_file_ar', models.FileField(blank=True, default=None, null=True, upload_to='audios_ar/')),
                ('EN_explanations', models.TextField(blank=True, default=None, null=True)),
                ('audio_file_en', models.FileField(blank=True, default=None, null=True, upload_to='audios_en/')),
                ('FR_explanations', models.TextField(blank=True, default=None, null=True)),
                ('audio_file_fr', models.FileField(blank=True, default=None, null=True, upload_to='audios_fr/')),
                ('HA_explanations', models.TextField(blank=True, default=None, null=True)),
                ('audio_file_ha', models.FileField(blank=True, default=None, null=True, upload_to='audios_ha/')),
                ('IG_explanations', models.TextField(blank=True, default=None, null=True)),
                ('audio_file_ig', models.FileField(blank=True, default=None, null=True, upload_to='audios_ig/')),
                ('YO_explanations', models.TextField(blank=True, default=None, null=True)),
                ('audio_file_yo', models.FileField(blank=True, default=None, null=True, upload_to='audios_yo/')),
                ('published', models.DateField(auto_now_add=True, null=True)),
                ('subject', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='alteernlingual_subjects.subject', verbose_name='subject')),
                ('topic', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='alteernlingual_subjects.topic', verbose_name='subject_topic')),
            ],
        ),
        migrations.CreateModel(
            name='SubjectSkillFollow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_skill_follow', to='alteernlingual_subjects.subjectskill', verbose_name='subject_skill')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SubjectFollow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_follow', to='alteernlingual_subjects.subject', verbose_name='subject')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
