# Generated by Django 3.2.5 on 2021-09-16 07:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Alteernlingual_topic', '0008_readcount'),
        ('alteernlingual_subjects', '0002_auto_20210916_0820'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='title')),
                ('description', models.TextField(blank=True, max_length=255, verbose_name='description')),
                ('language', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='Alteernlingual_topic.language')),
            ],
        ),
        migrations.AlterField(
            model_name='topic',
            name='subject',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='alteernlingual_subjects.subjects', verbose_name='subject'),
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
    ]
