# Generated by Django 3.2.5 on 2021-10-03 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alteernlingual_subjects', '0005_auto_20210929_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topiccontent',
            name='subject',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='alteernlingual_subjects.subject', verbose_name='subject'),
        ),
        migrations.AlterField(
            model_name='topiccontent',
            name='topic',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='alteernlingual_subjects.topic', verbose_name='subject_topic'),
        ),
    ]
