# Generated by Django 3.2.5 on 2021-08-13 11:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('middle_name', models.CharField(max_length=50, null=True)),
                ('phone_number', models.IntegerField(null=True)),
                ('date_of_birth', models.CharField(max_length=30, null=True)),
                ('Nationality', models.CharField(choices=[('UK', 'United KingDom'), ('US', 'UNITED STATE'), ('france', 'FRANCE'), ('china', 'CHINA'), ('czech republic', 'Czech Republic'), ('columbia', 'COLOMBIA')], default='UK', max_length=20)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
