# Generated by Django 3.2.5 on 2021-08-19 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alteernlingual_user', '0002_auto_20210813_1317'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=75, verbose_name='title')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='description')),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_title', models.CharField(max_length=100)),
                ('original_explanations', models.TextField()),
                ('en_title', models.CharField(max_length=100)),
                ('en_explanations', models.TextField()),
                ('ig_title', models.CharField(max_length=100)),
                ('ig_explanations', models.TextField()),
                ('ha_title', models.CharField(max_length=100)),
                ('ha_explanations', models.TextField()),
                ('yo_title', models.CharField(max_length=100)),
                ('yo_explanations', models.TextField()),
                ('fr_title', models.CharField(max_length=100)),
                ('fr_explanations', models.TextField()),
                ('ar_title', models.CharField(max_length=100)),
                ('ar_explanations', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='ltl',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'English'), (2, 'Igbo'), (3, 'Hausa'), (4, 'Yoruba'), (5, 'French'), (4, 'Arabic')], null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/avatars/'),
        ),
    ]
