# Generated by Django 3.2.5 on 2021-08-19 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alteernlingual_user', '0003_auto_20210819_0857'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='loi',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'English'), (2, 'Igbo'), (3, 'Hausa'), (4, 'Yoruba'), (5, 'French'), (4, 'Arabic')], null=True),
        ),
        migrations.AddField(
            model_name='topic',
            name='category',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='alteernlingual_user.category', verbose_name='category'),
        ),
    ]
