# Generated by Django 3.2.5 on 2021-08-19 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alteernlingual_user', '0004_auto_20210819_0930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='category',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='alteernlingual_user.category', verbose_name='category'),
        ),
    ]
