# Generated by Django 3.2.5 on 2021-08-19 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alteernlingual_user', '0005_alter_topic_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='alteernlingual_user.category', verbose_name='category'),
        ),
    ]
