# Generated by Django 3.2.5 on 2021-08-19 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alteernlingual_user', '0006_alter_topic_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='category',
        ),
    ]
