# Generated by Django 3.2.5 on 2021-08-19 08:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alteernlingual_user', '0007_remove_topic_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='category',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='alteernlingual_user.category', verbose_name='category'),
        ),
    ]
