# Generated by Django 3.2.5 on 2021-09-19 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alteernlingual_user', '0008_topic_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='category',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='number',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='zip',
        ),
        migrations.AddField(
            model_name='profile',
            name='country',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='loi',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'English'), (2, 'Igbo'), (3, 'Hausa'), (4, 'Yoruba'), (5, 'French'), (6, 'Arabic')], default=1, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='ltl',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'English'), (2, 'Igbo'), (3, 'Hausa'), (4, 'Yoruba'), (5, 'French'), (6, 'Arabic')], default=1, null=True),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Topic',
        ),
    ]
