# Generated by Django 3.2.5 on 2021-08-21 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alteernlingual_user', '0009_auto_20210819_1038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='loi',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'English'), (2, 'Igbo'), (3, 'Hausa'), (4, 'Yoruba'), (5, 'French'), (6, 'Arabic')], default=1, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='ltl',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'English'), (2, 'Igbo'), (3, 'Hausa'), (4, 'Yoruba'), (5, 'French'), (6, 'Arabic')], default=1, null=True),
        ),
    ]
