# Generated by Django 3.2.5 on 2021-09-19 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alteernlingual_user', '0009_auto_20210919_0602'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='loi',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='ltl',
        ),
    ]
